name: pr

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          version: latest

      - uses: biomejs/setup-biome@v2
        with:
          version: latest

      - run: bun install
      - run: bun run build
      - run: bun biome ci .
