name: pr

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: biomejs/setup-biome@v2

      - run: npm ci
      - run: npm run check
