name: Update package.json

on:
  workflow_dispatch:
    inputs:
      npm_version:
        description: '@kixelated/moq NPM version'
        required: true

jobs:
  update_package:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - name: Configure Git
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'

      - name: Update package.json
        run: |
          jq ".dependencies['@kixelated/moq'] = \"${{ github.event.inputs.npm_version }}\"" package.json > package.json.tmp
          mv package.json.tmp package.json

      - run: |
          git add .
          git commit -m "Update @kixelated/moq to version ${{ github.event.inputs.npm_version }}" || echo "No changes to commit"
          git push

